version: 0.2

phases:
  pre_build:
    commands:
      #- cd "$CODEBUILD_SRC_DIR"
      - terraform init
      - terraform validate

  build:
    commands:
      - terraform plan

  post_build:
    commands:
      - echo "Terraform plan completed on `date`"